name: ci/cd

on:
  push:
    branches: [ main, 'release/**', 'task/**', 'feature/**', 'epic/**']
    tags: ['**']
  pull_request:
    branches: [ main, 'release/**', 'task/**', 'feature/**', 'epic/**']

jobs:

  builds:
    name: New builds on OTP ${{ matrix.otp_version }} / ${{ matrix.os }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        otp_version: [22, 23, 24, 25, 26]
        rebar3-version: ['3.22.0']
        os: [ubuntu-latest]

    container:
      image: erlang:${{ matrix.otp_version }}

    steps:
    - uses: actions/checkout@v4
    - name: Compile
      run: rebar3 compile
    - name: Xref Checks
      run: rebar3 xref
    - name: Dialyzer
      run: rebar3 dialyzer
    - name: Run Unit Tests
      run: rebar3 as test eunit
    - name: Run Proper Tests
      run: rebar3 as test do proper -c
    - name: Check Coverage
      run: rebar3 as test cover -v --min_coverage=0

  old-builds:
    name: Old builds on OTP ${{ matrix.otp_version }} / ${{ matrix.os }}
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        otp_version: [21]
        os: ['ubuntu-20.04']

    container:
      image: erlang:${{ matrix.otp_version }}

    steps:
    - uses: actions/checkout@v4
    - name: Compile
      run: rebar3 compile
    - name: Xref Checks
      run: rebar3 xref
    - name: Dialyzer
      run: rebar3 dialyzer
    - name: Run Unit Tests
      run: rebar3 as test eunit
    - name: Run Proper Tests
      run: rebar3 as test do proper -c
    - name: Check Coverage
      run: rebar3 as test cover -v --min_coverage=0
